### PR TITLE
Update frontend react readme

### PR DESCRIPTION
**Pull request by jam-lock**

### CODE REVIEW

**Review by brendancol — CHANGES_REQUESTED** [review]
Can we wrap these commands for the Makefile. My thought is this should be some docker exec command right?

**Review by brendancol — COMMENTED** [review]
Would this run within the docker container?  @giancastro should we wrap these commands in the Makefile?

**Comment by brendancol** [comment]
- [ ] Add commands to Makefile #34 
- [ ] Update README with make commands instead of direct npm / yarn commands

**Comment by brendancol** [comment]
@jam-lock ping

**Comment by jam-lock** [comment]
@brendancol, I replaced all the npm commands for the README for make commands and added them to the frontend config file

**Comment by brendancol** [comment]
LTGM

**Pull request merged**
